--- 
apiVersion: v1
kind: Pod
metadata: 
  name: webserver
spec: 
  containers: 
    - 
      image: "docker.io/giriraj789/webserver:A"
      name: webservera
      ports: 
        - 
          containerPort: 8080
      volumeMounts: 
        - 
          mountPath: /var/www/html
          name: config-volume
  volumes: 
    - 
      name: config-volume
      configMap:
        name: data 
