apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/general/persistentvolume
    server: 192.168.124.30
