--- 
apiVersion: v1
kind: Pod
metadata: 
  name: version1
  labels: 
        app: webserver
        version: one
        region: india
spec: 
  containers: 
    - 
      image: "docker.io/giriraj789/version:1"
      name: version1
      ports: 
        - 
          containerPort: 8080
