apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    version: one
  name: version1
  selfLink: /api/v1/namespaces/v1/services/version1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    version: one
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
