apiVersion: v1
kind: Service
metadata:
  name: headless
  labels:
    app: webserver
spec:
  clusterIP: None
  selector:
    app: webserver
    - port: 8080
      name: webserver
  selector:
    app: webserver
